### PR TITLE
Fix docstring(s) attributed to the flamegpu namespace

### LINKED ISSUE #1149: Incorrectly located docstrings attribtuted to namespaces
From the API docs, some docstrings are being associated to the namespace rather than the class / file they are for. 

e.g. on https://docs.flamegpu.com/api/namespace_flamegpu.html

> Detailed Description
> Collection of cuda related utility methods for internal use. Mostly to allow for graceful handling of device resets when cuda is called by dtors
> 
> This header exists to allow a convenient way to switch between curand implementations
> 
> The main cuRVE header file for the CUDA Runtime Struct Variable Environment (cuRVE) Based off the following article http:// www.gamasutra.com/view/news/127915/InDepth_Quasi_CompileTime_String_Hashing.php This file contains definitions common to HostCurve and DeviceCurve
> 
> CUDA does not implement atomicAdd(double*, double) for pre-pascal GPUs, which do not have the underlying hardware instruction. A CAS based software implementation is required instead, which will be much slower. This implementation is based on the reference implementation prodived by the CUDA toolkit documentation.
> 
> THIS CLASS SHOULD NOT BE INCLUDED DIRECTLY Include File AgentVector.h instead Use AgentVector::CAgent instead of Class AgentVector_CAgent Use AgentVector::Agent instead of Class AgentVector_Agent
> 
> Prodvides a utility method to cleanup after flamegpu. Currently for the only implementation (CUDA) this resets all devices.
> 
> Utility namespace for handling of NVTX profiling markers/ranges, uses if constexpr to avoid runtime cost when disabled
> 
> Macro FLAMEGPU_USE_NVTX is defined via CMake to set the member constexpr
> 

E.g. the first part of that comes from 

https://github.com/FLAMEGPU/FLAMEGPU2/blob/e606d4c2bd3db24d548729339896d8e1a7196fd1/include/flamegpu/detail/cuda.cuh#L4-L8

Which is prior to the `flamegpu` namespace, rather than the nested `cuda` namspace. 

Moving that docstring to before the `namespace cuda` declaration would correctly associate it with the namespace.

https://github.com/FLAMEGPU/FLAMEGPU2/blob/e606d4c2bd3db24d548729339896d8e1a7196fd1/include/flamegpu/detail/cuda.cuh#L15-L16. 

We probably do want to have a docstring somewhere for the flamepgu namspace though to populate that page with a general comment. Could be in any file but flamepgu.h would be the best place?

---

There will likely also be other occurences of this, and other docstring issues, which we might want to resolve. Might just need to do a pass of the api docs at some point if time allows.

### PR DESCRIPTION
**Pull request by ptheywood**
Replaces docstring comments with regular multline comments where appropriate (`/**` -> `/*`)

Moves docstring comments to be correctly associated with the namespace where appropriate.

Adds a single explicit docstring comment for `flamegpu`, in `flamegpu/flamegpu.h`

Closes #1149

### CODE REVIEW

**Comment by ptheywood** [comment]
I've not thoroughly checked the full docs, there are too many pages, but I skipped all the explcitly documented namespaces in doxygen html output.

File: include/flamegpu/simulation/AgentVector_Agent.h [hunk 1]
```diff
@@ -1,8 +1,8 @@
 #ifndef INCLUDE_FLAMEGPU_SIMULATION_AGENTVECTOR_AGENT_H_
 #define INCLUDE_FLAMEGPU_SIMULATION_AGENTVECTOR_AGENT_H_
 
-/**
```
Comment (Robadob) [inline include/flamegpu/simulation/AgentVector_Agent.h:4]: Not sure why you're removing the second `**`, I always put them back in.

File: include/flamegpu/util/cleanup.h [hunk 2]
```diff
@@ -1,8 +1,8 @@
 #ifndef INCLUDE_FLAMEGPU_UTIL_CLEANUP_H_
 #define INCLUDE_FLAMEGPU_UTIL_CLEANUP_H_
 
-/**
```
Comment (Robadob) [inline include/flamegpu/util/cleanup.h:4]: Same here, also inconsistent with other changes in this PR.

**Review by Robadob — APPROVED** [review]
Grand scheme the stars are inconsequential, fixes are positive.

File: include/flamegpu/simulation/AgentVector_Agent.h (hunk 1 above)
Comment (ptheywood) [reply include/flamegpu/simulation/AgentVector_Agent.h:4]: ** makes it a docstring, not a multiline comment, which doxygen associates with the next namespace / class / mehtod it gets to, unless told otherwise. 

This is a file level comment, so not a docstring that should be assocated with a particular class nor namespace.

File: include/flamegpu/util/cleanup.h (hunk 2 above)
Comment (ptheywood) [reply include/flamegpu/util/cleanup.h:4]: its a file level multline comment, not a docstring about a particular namespace nor class (there isn't a cleanup specific namespace or class, just method(s)

**Comment by Robadob** [comment]
Fair, wasn't aware the difference!
